gaurdianSpec:
  image: docker.io/anvaari/connector-guardian:0.3.0
  replicas: 1
  resources:
    limits:
      cpu: 50m
      memory: 100Mi
    requests:
      cpu: 20m
      memory: 20Mi

guardianConfig:
  env:
    name: guardian-configs
    data:
      KAFKA_CONNECT_HOST: localhost
      KAFKA_CONNECT_USER: ''
      KAFKA_CONNECT_PASS: ''
      KAFKA_CONNECT_PORT: '8083'
      KAFKA_CONNECT_PROTOCOL: 'http'
      ENABLE_BACKOFF: '1'
      MAX_RESTART: '7'
      EXPONENTIAL_RATIO: '2'