guard: 
  image: docker.io/anvaari/connector-guardian:0.1.0
spec: 
  replicas: 1

containers: 
   resources:
     limits:
       cpu: 50m
       memory: 100Mi
     requests:
       cpu: 20m
       memory: 20Mi
   env:
     - name: KAFKA_CONNECT_HOST
       value: 'localhost'
     - name: KAFKA_CONNECT_USER
       value: ''
     - name: KAFKA_CONNECT_PASS
       value: ''
     - name: KAFKA_CONNECT_PORT
       value: '8083'
     - name: KAFKA_CONNECT_PROTO
       value: 'http'
