apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector-guardian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connector-guardian
  template:
    metadata:
      labels:
        app: connector-guardian
    spec:
      containers:
      - name: connector-guardian
        image: docker.io/anvaari/connector-guardian:0.2.0
        command: ["/bin/bash"]
        args: ["-c", "while true; do python /connector-guardian/connector_guardian.py; sleep 300; done"]
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 20Mi
        env:
          - name: KAFKA_CONNECT_HOST
            value: 'localhost'
          - name: KAFKA_CONNECT_USER
            value: ''
          - name: KAFKA_CONNECT_PASS
            value: ''
          - name: KAFKA_CONNECT_PORT
            value: '8083'
          - name: KAFKA_CONNECT_PROTOCOL
            value: 'http'
          - name: LOG_LEVEL
            value: 'info'
